import { TemplateMetadata, ResumeTemplateId } from "@/types/resume";

export const RESUME_TEMPLATES: TemplateMetadata[] = [
  // ==========================================
  // CATEGORY 1: ATS PROFESSIONAL (5)
  // ==========================================
  {
    id: "ats-classic",
    name: "ATS Classic",
    category: "ats",
    categoryName: "ATS Professional",
    description: "Ultra-clean single column monochrome layout with maximum machine-readability across Workday, Greenhouse, and Taleo.",
    tags: ["Single Column", "Monochrome", "100% ATS Safe", "High Readability"],
    atsScore: 100,
    popular: true,
    featured: true,
    bestFor: "Corporate, Banking, Enterprise, and Government roles",
    accentColors: ["#000000", "#1e293b", "#334155"],
    layoutType: "single-column",
  },
  {
    id: "ats-executive",
    name: "ATS Executive",
    category: "ats",
    categoryName: "ATS Professional",
    description: "Corporate appearance with strong typographic hierarchy, left accent borders, and structured leadership focus.",
    tags: ["Corporate", "Executive", "ATS Friendly", "Structured"],
    atsScore: 98,
    popular: true,
    bestFor: "Directors, Senior Managers, and C-Suite Professionals",
    accentColors: ["#1e3a8a", "#0f172a", "#312e81"],
    layoutType: "single-column",
  },
  {
    id: "ats-modern",
    name: "ATS Modern",
    category: "ats",
    categoryName: "ATS Professional",
    description: "Recruiter-friendly design with subtle color tags, modern spacing, and clean section dividers.",
    tags: ["Modern Accent", "Recruiter Friendly", "Clean Dividers"],
    atsScore: 96,
    bestFor: "Mid to Senior Professionals across all industries",
    accentColors: ["#0284c7", "#4f46e5", "#059669"],
    layoutType: "single-column",
  },
  {
    id: "ats-minimal",
    name: "ATS Minimal",
    category: "ats",
    categoryName: "ATS Professional",
    description: "High-density clean typography designed to fit substantial experience cleanly into a 1-page format.",
    tags: ["High Density", "1-Page Standard", "Minimalist"],
    atsScore: 99,
    bestFor: "Experienced candidates wanting a sleek 1-page resume",
    accentColors: ["#334155", "#0f172a", "#475569"],
    layoutType: "single-column",
  },
  {
    id: "ats-technical",
    name: "ATS Technical",
    category: "ats",
    categoryName: "ATS Professional",
    description: "Optimized for software engineers and technical recruiters with prominent skills categorization and project highlights.",
    tags: ["Software Engineers", "Technical Screening", "Skill Matrix"],
    atsScore: 97,
    popular: true,
    bestFor: "Developers, DevOps, Cloud Engineers, and Data Scientists",
    accentColors: ["#2563eb", "#059669", "#7c3aed"],
    layoutType: "single-column",
  },

  // ==========================================
  // CATEGORY 2: MODERN PROFESSIONAL (5)
  // ==========================================
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    category: "professional",
    categoryName: "Modern Professional",
    description: "Modern top banner header paired with a balanced 2-column sidebar layout for maximum visual impact.",
    tags: ["2-Column", "Color Header", "Corporate Impact"],
    atsScore: 92,
    popular: true,
    bestFor: "Corporate Strategy, Finance, Consulting, and Sales",
    accentColors: ["#1d4ed8", "#0284c7", "#4338ca"],
    layoutType: "two-column",
  },
  {
    id: "modern-executive",
    name: "Modern Executive",
    category: "professional",
    categoryName: "Modern Professional",
    description: "Distinguished badge headings with modern executive typography and strategic competency highlights.",
    tags: ["Badge Headings", "Executive", "Polished"],
    atsScore: 94,
    bestFor: "VP of Operations, Product Directors, and Senior Leads",
    accentColors: ["#0f766e", "#1e3a8a", "#991b1b"],
    layoutType: "single-column",
  },
  {
    id: "contemporary-pro",
    name: "Contemporary Professional",
    category: "professional",
    categoryName: "Modern Professional",
    description: "Rounded card containers with indigo accents and smooth visual flow across work milestones.",
    tags: ["Contemporary", "Card Containers", "Smooth Layout"],
    atsScore: 91,
    bestFor: "Tech Consultants, Project Managers, and Product Leads",
    accentColors: ["#6366f1", "#8b5cf6", "#3b82f6"],
    layoutType: "single-column",
  },
  {
    id: "elegant-business",
    name: "Elegant Business",
    category: "professional",
    categoryName: "Modern Professional",
    description: "Editorial serif typography with warm tones, high contrast, and refined European business aesthetics.",
    tags: ["Serif Typography", "Editorial", "Sophisticated"],
    atsScore: 93,
    bestFor: "Legal, Consulting, Wealth Management, and Advisory",
    accentColors: ["#7c2d12", "#1c1917", "#1e3a8a"],
    layoutType: "single-column",
  },
  {
    id: "premium-consultant",
    name: "Premium Consultant",
    category: "professional",
    categoryName: "Modern Professional",
    description: "Filled section titles with forest emerald accents tailored for consulting and case engagement resumes.",
    tags: ["Filled Titles", "Advisory", "Consulting"],
    atsScore: 95,
    bestFor: "McKinsey/Bain/BCG Consultants, Strategists, and Analysts",
    accentColors: ["#047857", "#0369a1", "#4338ca"],
    layoutType: "single-column",
  },

  // ==========================================
  // CATEGORY 3: SOFTWARE ENGINEER (4)
  // ==========================================
  {
    id: "developer-pro",
    name: "Developer Pro",
    category: "engineering",
    categoryName: "Software Engineer",
    description: "Engineering-focused layout spotlighting open source projects, GitHub repositories, and tech stacks.",
    tags: ["Open Source", "GitHub Links", "Project Grid"],
    atsScore: 95,
    popular: true,
    featured: true,
    bestFor: "Frontend, Backend, Full-Stack, and Mobile Engineers",
    accentColors: ["#3b82f6", "#10b981", "#8b5cf6"],
    layoutType: "single-column",
  },
  {
    id: "fullstack-engineer",
    name: "Full Stack Engineer",
    category: "engineering",
    categoryName: "Software Engineer",
    description: "Two-column technical layout with dedicated stacks sidebar and architecture-focused descriptions.",
    tags: ["2-Column Stack", "Full Stack", "Clean Architecture"],
    atsScore: 90,
    bestFor: "Senior Full-Stack, Cloud & DevOps Engineers",
    accentColors: ["#8b5cf6", "#4f46e5", "#06b6d4"],
    layoutType: "two-column",
  },
  {
    id: "tech-minimal",
    name: "Tech Minimal",
    category: "engineering",
    categoryName: "Software Engineer",
    description: "Terminal and monospace inspired minimalist design with clean ASCII-like section markers.",
    tags: ["Terminal Aesthetic", "Monospace", "Minimal"],
    atsScore: 98,
    bestFor: "Linux, Kernel, Backend, and Systems Engineers",
    accentColors: ["#09090b", "#334155", "#059669"],
    layoutType: "single-column",
  },
  {
    id: "engineering-portfolio",
    name: "Engineering Portfolio",
    category: "engineering",
    categoryName: "Software Engineer",
    description: "Dark carbon header with prominent project cards and interactive tech stack chips.",
    tags: ["Dark Banner", "Portfolio Cards", "Modern Tech"],
    atsScore: 92,
    bestFor: "Tech Leads, Engineering Managers, and Staff Engineers",
    accentColors: ["#059669", "#2563eb", "#d97706"],
    layoutType: "single-column",
  },

  // ==========================================
  // CATEGORY 4: CREATIVE DESIGNER (4)
  // ==========================================
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    category: "creative",
    categoryName: "Creative Designer",
    description: "Vibrant accent styling with case study callout cards and visual hierarchy designed to impress design leads.",
    tags: ["Vibrant Colors", "Case Studies", "UI/UX Focus"],
    atsScore: 88,
    popular: true,
    bestFor: "UI/UX Designers, Product Designers, and Creative Directors",
    accentColors: ["#ec4899", "#f43f5e", "#8b5cf6"],
    layoutType: "single-column",
  },
  {
    id: "designer-grid",
    name: "Designer Grid",
    category: "creative",
    categoryName: "Creative Designer",
    description: "12-column asymmetric grid layout showcasing selected works alongside tools and core methodologies.",
    tags: ["12-Column Grid", "Asymmetric", "Toolbox"],
    atsScore: 87,
    bestFor: "Graphic Designers, Brand Designers, and Animators",
    accentColors: ["#f97316", "#e11d48", "#0284c7"],
    layoutType: "two-column",
  },
  {
    id: "visual-artist",
    name: "Visual Artist",
    category: "creative",
    categoryName: "Creative Designer",
    description: "Atmospheric purple-indigo gradient header with spacious gallery card sections.",
    tags: ["Gradient Header", "Gallery Cards", "Artistic"],
    atsScore: 85,
    bestFor: "3D Artists, Motion Designers, and Creative Directors",
    accentColors: ["#a855f7", "#6366f1", "#ec4899"],
    layoutType: "single-column",
  },
  {
    id: "creative-modern",
    name: "Creative Modern",
    category: "creative",
    categoryName: "Creative Designer",
    description: "Modern teal accents with balanced two-column project and skills distributions.",
    tags: ["Modern Teal", "Balanced Columns", "Clean Creative"],
    atsScore: 91,
    bestFor: "Design Technologists, Design Systems Engineers, and PMs",
    accentColors: ["#14b8a6", "#06b6d4", "#3b82f6"],
    layoutType: "two-column",
  },

  // ==========================================
  // CATEGORY 5: STUDENT & FRESHER (3)
  // ==========================================
  {
    id: "graduate-starter",
    name: "Graduate Starter",
    category: "student",
    categoryName: "Student & Fresher",
    description: "Education-first layout highlighting GPA, coursework, academic projects, and internship experience.",
    tags: ["Education First", "GPA Highlight", "Coursework"],
    atsScore: 96,
    popular: true,
    bestFor: "College Graduates, Interns, and Entry-Level Candidates",
    accentColors: ["#2563eb", "#4f46e5", "#059669"],
    layoutType: "single-column",
  },
  {
    id: "campus-professional",
    name: "Campus Professional",
    category: "student",
    categoryName: "Student & Fresher",
    description: "Clean modern design highlighting campus leadership, hackathons, and technical projects.",
    tags: ["Campus Leadership", "Hackathons", "Clean Modern"],
    atsScore: 95,
    bestFor: "Students applying for Tech and Corporate Summer Internships",
    accentColors: ["#4f46e5", "#2563eb", "#7c3aed"],
    layoutType: "single-column",
  },
  {
    id: "fresher-ats",
    name: "Fresher ATS",
    category: "student",
    categoryName: "Student & Fresher",
    description: "Single-column high-compatibility ATS template formatted specifically for entry-level candidates.",
    tags: ["100% ATS Safe", "Entry Level", "Single Column"],
    atsScore: 100,
    bestFor: "Freshers seeking maximum pass-rate on online job portals",
    accentColors: ["#000000", "#1e293b", "#334155"],
    layoutType: "single-column",
  },

  // ==========================================
  // CATEGORY 6: PREMIUM SHOWCASE (4)
  // ==========================================
  {
    id: "luxury-black",
    name: "Luxury Black",
    category: "premium",
    categoryName: "Premium Showcase",
    description: "Deep carbon slate dark theme with platinum typography and high-end executive styling.",
    tags: ["Dark Mode", "Luxury Aesthetic", "Platinum Text"],
    atsScore: 90,
    popular: true,
    featured: true,
    bestFor: "Senior Tech Executives, Founders, and Creative Leads",
    accentColors: ["#e2e8f0", "#94a3b8", "#f8fafc"],
    layoutType: "single-column",
  },
  {
    id: "premium-gold",
    name: "Premium Gold",
    category: "premium",
    categoryName: "Premium Showcase",
    description: "Warm gold metallic accents and refined serif typography for distinguished C-level presence.",
    tags: ["Gold Accents", "Serif Typography", "Distinguished"],
    atsScore: 94,
    bestFor: "Managing Partners, Board Members, and Senior Executives",
    accentColors: ["#d97706", "#b45309", "#92400e"],
    layoutType: "single-column",
  },
  {
    id: "minimal-luxury",
    name: "Minimal Luxury",
    category: "premium",
    categoryName: "Premium Showcase",
    description: "Ultra-spacious high contrast minimalist luxury design with Swiss typographic rhythm.",
    tags: ["Swiss Typography", "High Contrast", "Minimal Luxury"],
    atsScore: 96,
    bestFor: "Design Directors, Luxury Brand Managers, and Architects",
    accentColors: ["#18181b", "#27272a", "#3f3f46"],
    layoutType: "single-column",
  },
  {
    id: "elite-executive",
    name: "Elite Executive",
    category: "premium",
    categoryName: "Premium Showcase",
    description: "Deep slate borders with authoritative leadership structure designed for C-Suite recruiting.",
    tags: ["C-Suite", "Board Ready", "Authoritative"],
    atsScore: 97,
    bestFor: "CTO, CEO, VP of Engineering, and Board Candidates",
    accentColors: ["#0f172a", "#1e293b", "#334155"],
    layoutType: "single-column",
  },
];
